Allow overriding filter or fields

diff --git a/awsdsv b/awsdsv
--- a/awsdsv
+++ b/awsdsv
@@ -2,20 +2,78 @@
 
 set -euo pipefail
 
+if ! PARSED=$(getopt -o "-j:f::a:q" --long filter:,fields::,add:,query -n "awsdsv" -- "$@"); then
+    echo "Usage: $0 [-j|--filter arg] [-f|--fields args...] [-a|--add args...] [ -q|--query ]"
+    exit 1
+fi
+
+eval set -- "$PARSED"
+
+fields=()
+additional_fields=()
+
+fields_arg_set=0
+query_arg_set=0
+
+while true; do
+    case "$1" in
+    -j | --filter)
+        shift
+        filter="$1"
+        shift
+        ;;
+    -f | --fields)
+        fields_arg_set=1
+        shift
+        while [[ $# -gt 0 && "$1" != -* ]]; do
+            if [[ -n "$1" ]]; then
+                fields+=("$1")
+            fi
+            shift
+        done
+        ;;
+    -a | --add)
+        shift
+        while [[ $# -gt 0 && "$1" != -* ]]; do
+            if [[ -n "$1" ]]; then
+                additional_fields+=("$1")
+            fi
+            shift
+        done
+        ;;
+    -q | --query)
+        query_arg_set=1
+        shift
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        echo "invalid args: $*"
+        exit
+        ;;
+    esac
+done
+
 get_leading_key() {
     jq -r 'keys[0]' "$1"
 }
 
+lookup_config_key() {
+    jq -r --arg KEY "$1" "$2" <<<"$3"
+}
+
 lookup_get_filter() {
-    jq -r --arg KEY "$1" '.[$KEY]?.filter // empty' <<<"$2"
+    lookup_config_key "$1" '.[$KEY]?.filter // empty' "$2"
 }
 
 lookup_get_fields() {
-    jq -r --arg KEY "$1" '.[$KEY]?.fields?.[]? // empty' <<<"$2"
+    lookup_config_key "$1" '.[$KEY]?.fields?.[]? // empty' "$2"
 }
 
 filter_fields() {
-    if [ $# -ne 0 ]; then
+    if [[ $# -ne 0 ]]; then
         dsv --pretty cut "$@"
     else
         dsv --pretty
@@ -39,18 +97,37 @@ cat >"$initial_response"
 key=$(get_leading_key "$initial_response")
 
 SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
-config=$(yq -r '.' "${CONFIG_FILE:-$SCRIPT_DIR/config.yaml}")
-filter=$(lookup_get_filter "$key" "$config")
+config=$(yq -r '.' "${AWSDSV_CONFIG_FILE:-$SCRIPT_DIR/config.yaml}")
 
-if [ -z "$filter" ]; then
+if [[ ! -v filter || -z "$filter" ]]; then
+    filter=$(lookup_get_filter "$key" "$config")
+fi
+
+if [[ ! -v filter || -z "$filter" ]]; then
     filter="map(arrays | .[])[]"
 fi
 
-readarray -t fields < <(lookup_get_fields "$key" "$config")
+if [[ "$fields_arg_set" == 0 ]]; then
+    readarray -t fields < <(lookup_get_fields "$key" "$config")
+fi
 
-all_fields=("${fields[@]}" "$@")
+all_fields=("${fields[@]}" "${additional_fields[@]}")
 
-jq "$filter" "$initial_response" |
-    jq 'walk(if . == "" or . == [] then empty else . end) | . + (.Tags // [] | map({("tag:" + .Key): .Value}) | add) | del(.Tags)' |
-    dsv fromjson |
-    filter_fields "${all_fields[@]}"
+base_filter='walk(if . == "" or . == [] then empty else . end) | . + (.Tags // [] | map({("tag:" + .Key): .Value}) | add) | del(.Tags)'
+
+if [[ "$query_arg_set" == 0 ]]; then
+    jq "$filter" "$initial_response" |
+        jq "$base_filter" |
+        dsv fromjson |
+        filter_fields "${all_fields[@]}"
+else
+    jq -n \
+        --arg filter "$filter" \
+        --argjson configured_fields \
+        "$(echo "${fields[@]}" | jq -R 'if . == "" then empty else . end' | jq -s)" \
+        --argjson additional_fields \
+        "$(echo "${additional_fields[@]}" | jq -R 'if . == "" then empty else . end' | jq -s)" \
+        --argjson available_fields \
+        "$(jq "$filter" "$initial_response" | jq "$base_filter" | jq -rs 'map(keys) | flatten | unique')" \
+        '$ARGS.named'
+fi
